version: '3'
services:
  database:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=cardanodb
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
